project_name: ecs-agent-updater
env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
builds:
  - main: .
    binary: ecs-agent-updater
    ldflags:
      - -s -w
      - -X main.Version={{.Version}}
      - -X main.Revision={{.ShortCommit}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    replacements:
      darwin: darwin
      linux: linux
      windows: windows
      386: i386
      amd64: x86_64
    format_overrides:
      - goos: windows
        format: zip
release:
  prerelease: auto

# homebrew
brews:
  - description: "update ECS agent with CLI."
    github:
      owner: reiki4040
      name: homebrew-tap
    homepage: "https://github.com/reiki4040/ecs-agent-updater"
    install: |
      bin.install "ecs-agent-updater"
    #caveats: "How to use this binary"
    #custom_block: # later use for devel version